### ISSUE TITLE
Maximize code coverage

### ISSUE THREAD

**Issue by stephlocke** [reconhub/reportfactory#63] opened 2020-03-23 18:05 UTC
These functions come up as no code coverage. Do you think they need tests before CRAN submission? If yes, who will tackle these?

R/archive_reports.R: 0.00%
R/clean_report_sources.R: 0.00%
R/install_deps.R: 0.00%
R/list_deps.R: 0.00%
R/list_outputs.R: 0.00%
R/rfh_load_scripts.R: 0.00%
R/update_reports.R: 0.00%

**Comment by thibautjombart** [comment] 2020-11-17 06:55
I suspect they do, but as most tests are not ran on cran the corresponding environment variable needs to be set up. At 8f173f257eecea193139e360399450fa1950bf56 I get:

```r
> Sys.setenv(NOT_CRAN = "true")
> covr::package_coverage()
reportfactory Coverage: 62.97%
R/archive_reports.R: 0.00%
R/filter_log_conditions.R: 0.00%
R/filter_log_most_recent.R: 0.00%
R/filter_log_output_types.R: 0.00%
R/filter_log_require_by_type.R: 0.00%
R/filter_log.R: 0.00%
R/install_deps.R: 0.00%
R/list_deps.R: 0.00%
R/ship_reports.R: 0.00%
R/update_reports.R: 72.00%
R/factory_path.R: 80.00%
R/list_outputs.R: 85.71%
R/list_reports.R: 91.67%
R/compile_report.R: 94.23%
R/add_to_log.R: 100.00%
R/clean_report_sources.R: 100.00%
R/create_log_entry.R: 100.00%
R/current_compile_log.R: 100.00%
R/extract_base.R: 100.00%
R/extract_date.R: 100.00%
R/extract_string.R: 100.00%
R/ignore_tilde.R: 100.00%
R/move_file.R: 100.00%
R/new_factory.R: 100.00%
R/random_alphanum.R: 100.00%
R/random_factory.R: 100.00%
R/rfh_load_scripts.R: 100.00%
R/validate_factory.R: 100.00%
```

**Comment by thibautjombart** [comment] 2021-01-14 10:45
Now fixed. Some tests disabled on windows due to weird issues on win builder we cannot reproduce.

**Closed by thibautjombart** 2021-01-14 10:45 UTC
Labels: enhancement
