### ISSUE TITLE
example files should not be compressed

### ISSUE THREAD

**Issue by zkamvar** [reconhub/reportfactory#11] opened 2019-05-22 08:41 UTC
The example files in `inst` are all compressed files. While these are great for easy deployment on the developer side, they are not so great for tracking changes, assessing what packages are needed to build them, transparency, and security. 

These need to be split up into individual files and have helper functions to move them around.

> Note: This was originally going to be part of my review that I started months ago

**Comment by zkamvar** [comment] 2019-05-30 14:31
This really should be a priority because I can't friggen test anything until I know exactly what packages are needed to compile the reports.

**Comment by zkamvar** [comment] 2019-05-30 14:32
but it's going to take a bit of effort since there is so much junk

**Comment by thibautjombart** [comment] 2020-11-17 06:49
I have made a first pass at this at https://github.com/reconhub/reportfactory/tree/issue_11

bumped into weird issue where tests pass with `devtools::test()` but fail with `devtools::check()`; seems related to some files missing when creating a new factory, but cannot reproduce the issue outside of the check

**Comment by thibautjombart** [comment] 2021-01-14 10:55
Fixed in CRAN release version.

**Closed by thibautjombart** 2021-01-14 10:55 UTC
Labels: help wanted
